name: TweakWarp
main: com.guntherdw.bukkit.TweakWarp.TweakWarp
version: 2.0b1
commands:
     warp:
        description: Warps you to a specific place
        usage: /<command> [name] <group>
        _permission: tweakwarp.warp
     setwarp:
        description: Creates a new warp
        usage: /<command> [name] <group>
        _permission: tweakwarp.setwarp
     removewarp:
        description: Removes a warp
        usage: /<command> [name] <group>
        _permission: tweakwarp.removewarp
     listwarps:
        description: Lists the current warps
        usage: /<command>
     reloadwarps:
        description: Reloads the warp table
        usage: /<command>
        _permission: tweakwarp.reloadwarps
     warpback:
        description: Toggle warp saving for tpback
        usage: /<command>
        _permission: tweakcraftutils.tpback